// Coletânea de palavras do Jogo do Impostor.
// Cada entrada: { p: palavra, d: PISTA (uma só palavra, OBLÍQUA), c: categoria }
// A pista é vista APENAS pelo impostor. Não deve ser a característica óbvia da palavra,
// mas uma associação lateral (contexto, alcunha, consequência, símbolo) que obrigue a pensar.
// Os nomes do grupo de amigos não têm pista (d: "").

const WORDS = [
  // ───────────────────────────── ANIMAIS ─────────────────────────────
  { p: "Leão", d: "Coragem", c: "Animais" },
  { p: "Golfinho", d: "Sonar", c: "Animais" },
  { p: "Pinguim", d: "Smoking", c: "Animais" },
  { p: "Camaleão", d: "Disfarce", c: "Animais" },
  { p: "Polvo", d: "Oito", c: "Animais" },
  { p: "Morcego", d: "Radar", c: "Animais" },
  { p: "Tartaruga", d: "Lebre", c: "Animais" },
  { p: "Coruja", d: "Sabedoria", c: "Animais" },
  { p: "Formiga", d: "Cigarra", c: "Animais" },
  { p: "Caracol", d: "Baba", c: "Animais" },
  { p: "Raposa", d: "Galinheiro", c: "Animais" },
  { p: "Abelha", d: "Rainha", c: "Animais" },
  { p: "Canguru", d: "Bolso", c: "Animais" },
  { p: "Camelo", d: "Oásis", c: "Animais" },
  { p: "Borboleta", d: "Metamorfose", c: "Animais" },
  { p: "Tubarão", d: "Cinema", c: "Animais" },
  { p: "Papagaio", d: "Pirata", c: "Animais" },
  { p: "Ouriço", d: "Bola", c: "Animais" },
  { p: "Lobo", d: "Lua", c: "Animais" },
  { p: "Cavalo", d: "Xadrez", c: "Animais" },

  // ──────────────────────────── PROFISSÕES ───────────────────────────
  { p: "Bombeiro", d: "Escada", c: "Profissões" },
  { p: "Professor", d: "Recreio", c: "Profissões" },
  { p: "Cozinheiro", d: "Estrela", c: "Profissões" },
  { p: "Piloto", d: "Nuvem", c: "Profissões" },
  { p: "Médico", d: "Receita", c: "Profissões" },
  { p: "Arquiteto", d: "Maqueta", c: "Profissões" },
  { p: "Jornalista", d: "Fonte", c: "Profissões" },
  { p: "Eletricista", d: "Choque", c: "Profissões" },
  { p: "Jardineiro", d: "Estação", c: "Profissões" },
  { p: "Advogado", d: "Cláusula", c: "Profissões" },
  { p: "Astronauta", d: "Gravidade", c: "Profissões" },
  { p: "Carteiro", d: "Cão", c: "Profissões" },
  { p: "Padeiro", d: "Madrugada", c: "Profissões" },
  { p: "Polícia", d: "Multa", c: "Profissões" },
  { p: "Dentista", d: "Sorriso", c: "Profissões" },
  { p: "Pescador", d: "Paciência", c: "Profissões" },
  { p: "Barbeiro", d: "Conversa", c: "Profissões" },
  { p: "Mecânico", d: "Mancha", c: "Profissões" },

  // ───────────────────────────── PLANTAS ─────────────────────────────
  { p: "Girassol", d: "Semente", c: "Plantas" },
  { p: "Cato", d: "Picada", c: "Plantas" },
  { p: "Carvalho", d: "Mesa", c: "Plantas" },
  { p: "Roseira", d: "Namorados", c: "Plantas" },
  { p: "Bambu", d: "Panda", c: "Plantas" },
  { p: "Trevo", d: "Irlanda", c: "Plantas" },
  { p: "Hortelã", d: "Mojito", c: "Plantas" },
  { p: "Videira", d: "Outono", c: "Plantas" },
  { p: "Oliveira", d: "Paz", c: "Plantas" },
  { p: "Nenúfar", d: "Monet", c: "Plantas" },
  { p: "Sequoia", d: "Califórnia", c: "Plantas" },

  // ────────────────────────────── COMIDA ─────────────────────────────
  { p: "Pastel de Nata", d: "Belém", c: "Comida" },
  { p: "Bacalhau", d: "Natal", c: "Comida" },
  { p: "Francesinha", d: "Porto", c: "Comida" },
  { p: "Piza", d: "Fatia", c: "Comida" },
  { p: "Sushi", d: "Cru", c: "Comida" },
  { p: "Hambúrguer", d: "Rápido", c: "Comida" },
  { p: "Gelado", d: "Verão", c: "Comida" },
  { p: "Caldo Verde", d: "Minho", c: "Comida" },
  { p: "Chocolate", d: "Páscoa", c: "Comida" },
  { p: "Sardinha", d: "Junho", c: "Comida" },
  { p: "Esparguete", d: "Novelo", c: "Comida" },
  { p: "Café", d: "Insónia", c: "Comida" },

  // ─────────────────────────────── LUGARES ───────────────────────────
  { p: "Praia", d: "Toalha", c: "Lugares" },
  { p: "Aeroporto", d: "Adeus", c: "Lugares" },
  { p: "Biblioteca", d: "Sussurro", c: "Lugares" },
  { p: "Hospital", d: "Espera", c: "Lugares" },
  { p: "Ginásio", d: "Janeiro", c: "Lugares" },
  { p: "Cinema", d: "Estreia", c: "Lugares" },
  { p: "Mercado", d: "Regateio", c: "Lugares" },
  { p: "Lisboa", d: "Sete", c: "Lugares" },
  { p: "Porto", d: "Ribeira", c: "Lugares" },
  { p: "Castelo", d: "Princesa", c: "Lugares" },
  { p: "Farol", d: "Aviso", c: "Lugares" },

  // ────────────────────────────── OBJETOS ────────────────────────────
  { p: "Guarda-chuva", d: "Esquecido", c: "Objetos" },
  { p: "Espelho", d: "Vaidade", c: "Objetos" },
  { p: "Relógio", d: "Pressa", c: "Objetos" },
  { p: "Chave", d: "Segredo", c: "Objetos" },
  { p: "Bússola", d: "Perdido", c: "Objetos" },
  { p: "Vela", d: "Aniversário", c: "Objetos" },
  { p: "Telemóvel", d: "Bateria", c: "Objetos" },
  { p: "Almofada", d: "Sonho", c: "Objetos" },
  { p: "Óculos", d: "Foco", c: "Objetos" },
  { p: "Mala", d: "Férias", c: "Objetos" },

  // ────────────────────────── CELEBRIDADES ───────────────────────────
  { p: "Cristiano Ronaldo", d: "Madeira", c: "Celebridades" },
  { p: "Lionel Messi", d: "Pulga", c: "Celebridades" },
  { p: "Beyoncé", d: "Colmeia", c: "Celebridades" },
  { p: "Elon Musk", d: "Marte", c: "Celebridades" },
  { p: "Taylor Swift", d: "Gatos", c: "Celebridades" },
  { p: "Leonardo DiCaprio", d: "Ambiente", c: "Celebridades" },
  { p: "Dwayne Johnson", d: "Pedra", c: "Celebridades" },
  { p: "Rihanna", d: "Barbados", c: "Celebridades" },
  { p: "Keanu Reeves", d: "Pílula", c: "Celebridades" },
  { p: "Lady Gaga", d: "Carne", c: "Celebridades" },
  { p: "Will Smith", d: "Estalo", c: "Celebridades" },
  { p: "Adele", d: "Lágrimas", c: "Celebridades" },

  // ───────────────────── PERSONALIDADES PORTUGUESAS ──────────────────
  { p: "Marcelo Rebelo de Sousa", d: "Banho", c: "Personalidades PT" },
  { p: "Salvador Sobral", d: "Coração", c: "Personalidades PT" },
  { p: "José Mourinho", d: "Especial", c: "Personalidades PT" },
  { p: "Amália Rodrigues", d: "Saudade", c: "Personalidades PT" },
  { p: "Luís de Camões", d: "Olho", c: "Personalidades PT" },
  { p: "Eusébio", d: "Pantera", c: "Personalidades PT" },
  { p: "Herman José", d: "Riso", c: "Personalidades PT" },
  { p: "Pedro Pascal", d: "Capacete", c: "Personalidades PT" },
  { p: "Fernando Pessoa", d: "Máscaras", c: "Personalidades PT" },
  { p: "Mariza", d: "Platina", c: "Personalidades PT" },
  { p: "Rui Costa", d: "Maestro", c: "Personalidades PT" },

  // ───────────────────────── ARTISTAS MUSICAIS ───────────────────────
  { p: "The Weeknd", d: "Néon", c: "Música" },
  { p: "Drake", d: "Coruja", c: "Música" },
  { p: "Billie Eilish", d: "Verde", c: "Música" },
  { p: "Bad Bunny", d: "Coelho", c: "Música" },
  { p: "Coldplay", d: "Cores", c: "Música" },
  { p: "Dua Lipa", d: "Regras", c: "Música" },
  { p: "Eminem", d: "Detroit", c: "Música" },
  { p: "Sam the Kid", d: "Almada", c: "Música" },
  { p: "Quim Barreiros", d: "Acordeão", c: "Música" },
  { p: "Xutos & Pontapés", d: "Bairro", c: "Música" },
  { p: "D.A.M.A", d: "Iniciais", c: "Música" },

  // ──────────────────── FILMES, SÉRIES E PERSONAGENS ─────────────────
  { p: "Titanic", d: "Iceberg", c: "Filmes & Séries" },
  { p: "Harry Potter", d: "Cicatriz", c: "Filmes & Séries" },
  { p: "Star Wars", d: "Pai", c: "Filmes & Séries" },
  { p: "Batman", d: "Mordomo", c: "Filmes & Séries" },
  { p: "Shrek", d: "Pântano", c: "Filmes & Séries" },
  { p: "Breaking Bad", d: "Carrinha", c: "Filmes & Séries" },
  { p: "Game of Thrones", d: "Inverno", c: "Filmes & Séries" },
  { p: "Friends", d: "Sofá", c: "Filmes & Séries" },
  { p: "Stranger Things", d: "Bicicleta", c: "Filmes & Séries" },
  { p: "Toy Story", d: "Cowboy", c: "Filmes & Séries" },
  { p: "La Casa de Papel", d: "Dalí", c: "Filmes & Séries" },
  { p: "Homem-Aranha", d: "Tio", c: "Filmes & Séries" },
  { p: "Frozen", d: "Irmãs", c: "Filmes & Séries" },
  { p: "O Senhor dos Anéis", d: "Vulcão", c: "Filmes & Séries" },

  // ───────────────── YOUTUBERS E INFLUENCERS PORTUGUESES ─────────────
  { p: "Wuant", d: "Pioneiro", c: "Youtubers PT" },
  { p: "SirKazzio", d: "Terror", c: "Youtubers PT" },
  { p: "Windoh", d: "Janela", c: "Youtubers PT" },
  { p: "Tiagovski", d: "Crítica", c: "Youtubers PT" },
  { p: "Fred (Maria Leal)", d: "Sarcasmo", c: "Youtubers PT" },
  { p: "D4rkFrame", d: "Sombra", c: "Youtubers PT" },
  { p: "Sofia Barbosa", d: "Beleza", c: "Youtubers PT" },
  { p: "Bumba na Fofinha", d: "Estrada", c: "Youtubers PT" },
  { p: "Luís e Maria", d: "Dois", c: "Youtubers PT" },
  { p: "Pi", d: "Número", c: "Youtubers PT" },

  // ───────────────────────────── BRAINROT ────────────────────────────
  { p: "Skibidi", d: "Sanita", c: "Brainrot" },
  { p: "Rizz", d: "Charme", c: "Brainrot" },
  { p: "Gyatt", d: "Trás", c: "Brainrot" },
  { p: "Sigma", d: "Sozinho", c: "Brainrot" },
  { p: "Ohio", d: "Estranho", c: "Brainrot" },
  { p: "Mewing", d: "Maxilar", c: "Brainrot" },
  { p: "NPC", d: "Repetição", c: "Brainrot" },
  { p: "Goofy ahh", d: "Disney", c: "Brainrot" },
  { p: "Fanum Tax", d: "Roubo", c: "Brainrot" },
  { p: "Tralalero Tralala", d: "Ténis", c: "Brainrot" },
  { p: "Bombardiro Crocodilo", d: "Avião", c: "Brainrot" },
  { p: "Tung Tung Sahur", d: "Ramadão", c: "Brainrot" },
  { p: "Aura", d: "Pontos", c: "Brainrot" },
  { p: "Gooning", d: "Horas", c: "Brainrot" },

  // ───────────────────────────── PORTUGAL ────────────────────────────
  { p: "Fado", d: "Casa", c: "Portugal" },
  { p: "Azulejo", d: "Fachada", c: "Portugal" },
  { p: "Saudade", d: "Tradução", c: "Portugal" },
  { p: "Galo de Barcelos", d: "Lenda", c: "Portugal" },
  { p: "25 de Abril", d: "Cravo", c: "Portugal" },
  { p: "Torre de Belém", d: "Descobrimentos", c: "Portugal" },
  { p: "Cristo Rei", d: "Braços", c: "Portugal" },
  { p: "Eléctrico 28", d: "Colina", c: "Portugal" },
  { p: "Vinho do Porto", d: "Sobremesa", c: "Portugal" },
  { p: "Tejo", d: "Margem", c: "Portugal" },
  { p: "Rancho Folclórico", d: "Aldeia", c: "Portugal" },

  // ───────────────────────────── FUTEBOL ─────────────────────────────
  { p: "Benfica", d: "Águia", c: "Futebol" },
  { p: "Sporting", d: "Alvalade", c: "Futebol" },
  { p: "FC Porto", d: "Dragão", c: "Futebol" },
  { p: "Penálti", d: "Onze", c: "Futebol" },
  { p: "VAR", d: "Ecrã", c: "Futebol" },
  { p: "Hat-trick", d: "Três", c: "Futebol" },
  { p: "Árbitro", d: "Apito", c: "Futebol" },
  { p: "Seleção", d: "Vermelho", c: "Futebol" },
  { p: "Golo", d: "Rede", c: "Futebol" },
  { p: "Luís Figo", d: "Traição", c: "Futebol" },
  { p: "Pauleta", d: "Festejo", c: "Futebol" },
  { p: "Cartão Vermelho", d: "Cedo", c: "Futebol" },

  // ───────────────────────────── DROGAS ──────────────────────────────
  { p: "Cocaína", d: "Branco", c: "Drogas" },
  { p: "Heroína", d: "Agulha", c: "Drogas" },
  { p: "Ecstasy", d: "Pista", c: "Drogas" },
  { p: "LSD", d: "Viagem", c: "Drogas" },
  { p: "Cogumelos", d: "Floresta", c: "Drogas" },
  { p: "MDMA", d: "Suor", c: "Drogas" },
  { p: "Ketamina", d: "Cavalo", c: "Drogas" },
  { p: "Anfetaminas", d: "Acordado", c: "Drogas" },

  // ────────────────────────────── WEED ───────────────────────────────
  { p: "Ganza", d: "Lento", c: "Weed" },
  { p: "Charro", d: "Enrolar", c: "Weed" },
  { p: "Erva", d: "Folha", c: "Weed" },
  { p: "Liamba", d: "Planta", c: "Weed" },
  { p: "Beck", d: "Pequeno", c: "Weed" },
  { p: "THC", d: "Sigla", c: "Weed" },
  { p: "Grinder", d: "Moer", c: "Weed" },
  { p: "Bong", d: "Água", c: "Weed" },
  { p: "Munchies", d: "Frigorífico", c: "Weed" },

  // ──────────────────────── SLANG PORTUGUÊS ──────────────────────────
  { p: "Fixe", d: "Aprovação", c: "Slang PT" },
  { p: "Bué", d: "Quantidade", c: "Slang PT" },
  { p: "Cota", d: "Idade", c: "Slang PT" },
  { p: "Bazar", d: "Saída", c: "Slang PT" },
  { p: "Gajo", d: "Pessoa", c: "Slang PT" },
  { p: "Piela", d: "Copos", c: "Slang PT" },
  { p: "Cromo", d: "Escola", c: "Slang PT" },
  { p: "Marado", d: "Cabeça", c: "Slang PT" },
  { p: "Curtir", d: "Diversão", c: "Slang PT" },
  { p: "Tasca", d: "Petisco", c: "Slang PT" },
  { p: "Cusco", d: "Bisbilhoteiro", c: "Slang PT" },
  { p: "Ganda", d: "Tamanho", c: "Slang PT" },

  // ──────────── GRUPO DE AMIGOS (sem pista — só o nome) ──────────────
  { p: "Rebelo", d: "", c: "Amigos" },
  { p: "Santos", d: "", c: "Amigos" },
  { p: "Marco", d: "", c: "Amigos" },
  { p: "Nuno", d: "", c: "Amigos" },
  { p: "Vitor", d: "", c: "Amigos" },
  { p: "Alex", d: "", c: "Amigos" },
  { p: "Freire", d: "", c: "Amigos" },
  { p: "Cunha", d: "", c: "Amigos" },
  { p: "Ribeiro", d: "", c: "Amigos" },
];

// Disponibiliza globalmente
if (typeof window !== "undefined") window.WORDS = WORDS;
