// Coletânea de palavras do Jogo do Impostor.
// Cada entrada: { p: palavra, d: PISTA (uma só palavra relacionada, subtil), c: categoria }
// A pista é vista APENAS pelo impostor. Deve ser uma palavra relacionada com a palavra
// sorteada, mas não óbvia. Os nomes do grupo de amigos não têm pista (d: "").
// Para acrescentar: copia uma linha e edita.

const WORDS = [
  // ───────────────────────────── ANIMAIS ─────────────────────────────
  { p: "Leão", d: "Savana", c: "Animais" },
  { p: "Golfinho", d: "Onda", c: "Animais" },
  { p: "Pinguim", d: "Gelo", c: "Animais" },
  { p: "Camaleão", d: "Cor", c: "Animais" },
  { p: "Polvo", d: "Tinta", c: "Animais" },
  { p: "Morcego", d: "Caverna", c: "Animais" },
  { p: "Tartaruga", d: "Casco", c: "Animais" },
  { p: "Coruja", d: "Noite", c: "Animais" },
  { p: "Formiga", d: "Colónia", c: "Animais" },
  { p: "Caracol", d: "Rasto", c: "Animais" },
  { p: "Raposa", d: "Astúcia", c: "Animais" },
  { p: "Abelha", d: "Pólen", c: "Animais" },
  { p: "Canguru", d: "Salto", c: "Animais" },
  { p: "Camelo", d: "Deserto", c: "Animais" },
  { p: "Borboleta", d: "Casulo", c: "Animais" },
  { p: "Tubarão", d: "Barbatana", c: "Animais" },
  { p: "Papagaio", d: "Trópico", c: "Animais" },
  { p: "Ouriço", d: "Espinho", c: "Animais" },
  { p: "Lobo", d: "Alcateia", c: "Animais" },
  { p: "Cavalo", d: "Galope", c: "Animais" },

  // ──────────────────────────── PROFISSÕES ───────────────────────────
  { p: "Bombeiro", d: "Chama", c: "Profissões" },
  { p: "Professor", d: "Quadro", c: "Profissões" },
  { p: "Cozinheiro", d: "Tacho", c: "Profissões" },
  { p: "Piloto", d: "Altitude", c: "Profissões" },
  { p: "Médico", d: "Bata", c: "Profissões" },
  { p: "Arquiteto", d: "Planta", c: "Profissões" },
  { p: "Jornalista", d: "Manchete", c: "Profissões" },
  { p: "Eletricista", d: "Tensão", c: "Profissões" },
  { p: "Jardineiro", d: "Tesoura", c: "Profissões" },
  { p: "Advogado", d: "Tribunal", c: "Profissões" },
  { p: "Astronauta", d: "Órbita", c: "Profissões" },
  { p: "Carteiro", d: "Selo", c: "Profissões" },
  { p: "Padeiro", d: "Farinha", c: "Profissões" },
  { p: "Polícia", d: "Patrulha", c: "Profissões" },
  { p: "Dentista", d: "Broca", c: "Profissões" },
  { p: "Pescador", d: "Anzol", c: "Profissões" },
  { p: "Barbeiro", d: "Navalha", c: "Profissões" },
  { p: "Mecânico", d: "Óleo", c: "Profissões" },

  // ───────────────────────────── PLANTAS ─────────────────────────────
  { p: "Girassol", d: "Sol", c: "Plantas" },
  { p: "Cato", d: "Sede", c: "Plantas" },
  { p: "Carvalho", d: "Bolota", c: "Plantas" },
  { p: "Roseira", d: "Perfume", c: "Plantas" },
  { p: "Bambu", d: "Panda", c: "Plantas" },
  { p: "Trevo", d: "Sorte", c: "Plantas" },
  { p: "Hortelã", d: "Frescura", c: "Plantas" },
  { p: "Videira", d: "Cacho", c: "Plantas" },
  { p: "Oliveira", d: "Azeite", c: "Plantas" },
  { p: "Nenúfar", d: "Lago", c: "Plantas" },
  { p: "Sequoia", d: "Altura", c: "Plantas" },

  // ────────────────────────────── COMIDA ─────────────────────────────
  { p: "Pastel de Nata", d: "Canela", c: "Comida" },
  { p: "Bacalhau", d: "Sal", c: "Comida" },
  { p: "Francesinha", d: "Molho", c: "Comida" },
  { p: "Piza", d: "Forno", c: "Comida" },
  { p: "Sushi", d: "Pauzinhos", c: "Comida" },
  { p: "Hambúrguer", d: "Pão", c: "Comida" },
  { p: "Gelado", d: "Frio", c: "Comida" },
  { p: "Caldo Verde", d: "Couve", c: "Comida" },
  { p: "Chocolate", d: "Cacau", c: "Comida" },
  { p: "Sardinha", d: "Brasa", c: "Comida" },
  { p: "Esparguete", d: "Garfo", c: "Comida" },
  { p: "Café", d: "Manhã", c: "Comida" },

  // ─────────────────────────────── LUGARES ───────────────────────────
  { p: "Praia", d: "Areia", c: "Lugares" },
  { p: "Aeroporto", d: "Mala", c: "Lugares" },
  { p: "Biblioteca", d: "Silêncio", c: "Lugares" },
  { p: "Hospital", d: "Urgência", c: "Lugares" },
  { p: "Ginásio", d: "Suor", c: "Lugares" },
  { p: "Cinema", d: "Pipocas", c: "Lugares" },
  { p: "Mercado", d: "Banca", c: "Lugares" },
  { p: "Lisboa", d: "Colinas", c: "Lugares" },
  { p: "Porto", d: "Ponte", c: "Lugares" },
  { p: "Castelo", d: "Muralha", c: "Lugares" },
  { p: "Farol", d: "Luz", c: "Lugares" },

  // ────────────────────────────── OBJETOS ────────────────────────────
  { p: "Guarda-chuva", d: "Tempestade", c: "Objetos" },
  { p: "Espelho", d: "Reflexo", c: "Objetos" },
  { p: "Relógio", d: "Ponteiro", c: "Objetos" },
  { p: "Chave", d: "Fechadura", c: "Objetos" },
  { p: "Bússola", d: "Norte", c: "Objetos" },
  { p: "Vela", d: "Cera", c: "Objetos" },
  { p: "Telemóvel", d: "Ecrã", c: "Objetos" },
  { p: "Almofada", d: "Sono", c: "Objetos" },
  { p: "Óculos", d: "Lente", c: "Objetos" },
  { p: "Mala", d: "Viagem", c: "Objetos" },

  // ────────────────────────── CELEBRIDADES ───────────────────────────
  { p: "Cristiano Ronaldo", d: "Madeira", c: "Celebridades" },
  { p: "Lionel Messi", d: "Pulga", c: "Celebridades" },
  { p: "Beyoncé", d: "Diva", c: "Celebridades" },
  { p: "Elon Musk", d: "Foguetão", c: "Celebridades" },
  { p: "Taylor Swift", d: "Country", c: "Celebridades" },
  { p: "Leonardo DiCaprio", d: "Óscar", c: "Celebridades" },
  { p: "Dwayne Johnson", d: "Rocha", c: "Celebridades" },
  { p: "Rihanna", d: "Maquilhagem", c: "Celebridades" },
  { p: "Keanu Reeves", d: "Matrix", c: "Celebridades" },
  { p: "Lady Gaga", d: "Pôquer", c: "Celebridades" },
  { p: "Will Smith", d: "Príncipe", c: "Celebridades" },
  { p: "Adele", d: "Balada", c: "Celebridades" },

  // ───────────────────── PERSONALIDADES PORTUGUESAS ──────────────────
  { p: "Marcelo Rebelo de Sousa", d: "Selfie", c: "Personalidades PT" },
  { p: "Salvador Sobral", d: "Coração", c: "Personalidades PT" },
  { p: "José Mourinho", d: "Especial", c: "Personalidades PT" },
  { p: "Amália Rodrigues", d: "Fado", c: "Personalidades PT" },
  { p: "Luís de Camões", d: "Lusíadas", c: "Personalidades PT" },
  { p: "Eusébio", d: "Pantera", c: "Personalidades PT" },
  { p: "Herman José", d: "Humor", c: "Personalidades PT" },
  { p: "Pedro Pascal", d: "Guardião", c: "Personalidades PT" },
  { p: "Fernando Pessoa", d: "Heterónimo", c: "Personalidades PT" },
  { p: "Mariza", d: "Platina", c: "Personalidades PT" },
  { p: "Rui Costa", d: "Pedal", c: "Personalidades PT" },

  // ───────────────────────── ARTISTAS MUSICAIS ───────────────────────
  { p: "The Weeknd", d: "Néon", c: "Música" },
  { p: "Drake", d: "Toronto", c: "Música" },
  { p: "Billie Eilish", d: "Sussurro", c: "Música" },
  { p: "Bad Bunny", d: "Coelho", c: "Música" },
  { p: "Coldplay", d: "Estrelas", c: "Música" },
  { p: "Dua Lipa", d: "Regras", c: "Música" },
  { p: "Eminem", d: "Rap", c: "Música" },
  { p: "Sam the Kid", d: "Rima", c: "Música" },
  { p: "Quim Barreiros", d: "Acordeão", c: "Música" },
  { p: "Xutos & Pontapés", d: "Rock", c: "Música" },
  { p: "D.A.M.A", d: "Pop", c: "Música" },

  // ──────────────────── FILMES, SÉRIES E PERSONAGENS ─────────────────
  { p: "Titanic", d: "Iceberg", c: "Filmes & Séries" },
  { p: "Harry Potter", d: "Varinha", c: "Filmes & Séries" },
  { p: "Star Wars", d: "Galáxia", c: "Filmes & Séries" },
  { p: "Batman", d: "Gotham", c: "Filmes & Séries" },
  { p: "Shrek", d: "Pântano", c: "Filmes & Séries" },
  { p: "Breaking Bad", d: "Química", c: "Filmes & Séries" },
  { p: "Game of Thrones", d: "Trono", c: "Filmes & Séries" },
  { p: "Friends", d: "Café", c: "Filmes & Séries" },
  { p: "Stranger Things", d: "Avesso", c: "Filmes & Séries" },
  { p: "Toy Story", d: "Brinquedo", c: "Filmes & Séries" },
  { p: "La Casa de Papel", d: "Máscara", c: "Filmes & Séries" },
  { p: "Homem-Aranha", d: "Teia", c: "Filmes & Séries" },
  { p: "Frozen", d: "Neve", c: "Filmes & Séries" },
  { p: "O Senhor dos Anéis", d: "Anel", c: "Filmes & Séries" },

  // ───────────────── YOUTUBERS E INFLUENCERS PORTUGUESES ─────────────
  { p: "Wuant", d: "Gaming", c: "Youtubers PT" },
  { p: "SirKazzio", d: "Grito", c: "Youtubers PT" },
  { p: "Windoh", d: "Plateau", c: "Youtubers PT" },
  { p: "Tiagovski", d: "Reação", c: "Youtubers PT" },
  { p: "Fred (Maria Leal)", d: "Comentário", c: "Youtubers PT" },
  { p: "D4rkFrame", d: "Escuridão", c: "Youtubers PT" },
  { p: "Sofia Barbosa", d: "Rotina", c: "Youtubers PT" },
  { p: "Bumba na Fofinha", d: "Carro", c: "Youtubers PT" },
  { p: "Luís e Maria", d: "Casal", c: "Youtubers PT" },
  { p: "Pi", d: "Música", c: "Youtubers PT" },

  // ───────────────────────────── BRAINROT ────────────────────────────
  { p: "Skibidi", d: "Sanita", c: "Brainrot" },
  { p: "Rizz", d: "Conquista", c: "Brainrot" },
  { p: "Gyatt", d: "Espanto", c: "Brainrot" },
  { p: "Sigma", d: "Macho", c: "Brainrot" },
  { p: "Ohio", d: "Estranho", c: "Brainrot" },
  { p: "Mewing", d: "Língua", c: "Brainrot" },
  { p: "NPC", d: "Robô", c: "Brainrot" },
  { p: "Goofy ahh", d: "Parvo", c: "Brainrot" },
  { p: "Fanum Tax", d: "Comida", c: "Brainrot" },
  { p: "Tralalero Tralala", d: "Ténis", c: "Brainrot" },
  { p: "Bombardiro Crocodilo", d: "Avião", c: "Brainrot" },
  { p: "Tung Tung Sahur", d: "Tambor", c: "Brainrot" },
  { p: "Aura", d: "Pontos", c: "Brainrot" },
  { p: "Gooning", d: "Vício", c: "Brainrot" },

  // ───────────────────────────── PORTUGAL ────────────────────────────
  { p: "Fado", d: "Guitarra", c: "Portugal" },
  { p: "Azulejo", d: "Parede", c: "Portugal" },
  { p: "Saudade", d: "Sentimento", c: "Portugal" },
  { p: "Galo de Barcelos", d: "Barro", c: "Portugal" },
  { p: "25 de Abril", d: "Cravo", c: "Portugal" },
  { p: "Torre de Belém", d: "Rio", c: "Portugal" },
  { p: "Cristo Rei", d: "Braços", c: "Portugal" },
  { p: "Eléctrico 28", d: "Turista", c: "Portugal" },
  { p: "Vinho do Porto", d: "Cálice", c: "Portugal" },
  { p: "Tejo", d: "Margem", c: "Portugal" },
  { p: "Rancho Folclórico", d: "Saia", c: "Portugal" },

  // ───────────────────────────── FUTEBOL ─────────────────────────────
  { p: "Benfica", d: "Águia", c: "Futebol" },
  { p: "Sporting", d: "Alvalade", c: "Futebol" },
  { p: "FC Porto", d: "Dragão", c: "Futebol" },
  { p: "Penálti", d: "Marca", c: "Futebol" },
  { p: "VAR", d: "Vídeo", c: "Futebol" },
  { p: "Hat-trick", d: "Três", c: "Futebol" },
  { p: "Árbitro", d: "Apito", c: "Futebol" },
  { p: "Seleção", d: "Vermelho", c: "Futebol" },
  { p: "Golo", d: "Rede", c: "Futebol" },
  { p: "Luís Figo", d: "Traição", c: "Futebol" },
  { p: "Pauleta", d: "Festejo", c: "Futebol" },
  { p: "Cartão Vermelho", d: "Expulsão", c: "Futebol" },

  // ───────────────────────────── DROGAS ──────────────────────────────
  { p: "Cocaína", d: "Pó", c: "Drogas" },
  { p: "Heroína", d: "Agulha", c: "Drogas" },
  { p: "Ecstasy", d: "Pista", c: "Drogas" },
  { p: "LSD", d: "Alucinação", c: "Drogas" },
  { p: "Cogumelos", d: "Floresta", c: "Drogas" },
  { p: "MDMA", d: "Festa", c: "Drogas" },
  { p: "Ketamina", d: "Veterinário", c: "Drogas" },
  { p: "Anfetaminas", d: "Energia", c: "Drogas" },

  // ────────────────────────────── WEED ───────────────────────────────
  { p: "Ganza", d: "Fumo", c: "Weed" },
  { p: "Charro", d: "Enrolar", c: "Weed" },
  { p: "Erva", d: "Folha", c: "Weed" },
  { p: "Liamba", d: "Planta", c: "Weed" },
  { p: "Beck", d: "Pequeno", c: "Weed" },
  { p: "THC", d: "Efeito", c: "Weed" },
  { p: "Grinder", d: "Moer", c: "Weed" },
  { p: "Bong", d: "Água", c: "Weed" },
  { p: "Munchies", d: "Fome", c: "Weed" },

  // ──────────────────────── SLANG PORTUGUÊS ──────────────────────────
  { p: "Fixe", d: "Aprovação", c: "Slang PT" },
  { p: "Bué", d: "Quantidade", c: "Slang PT" },
  { p: "Cota", d: "Idade", c: "Slang PT" },
  { p: "Bazar", d: "Saída", c: "Slang PT" },
  { p: "Gajo", d: "Pessoa", c: "Slang PT" },
  { p: "Piela", d: "Copos", c: "Slang PT" },
  { p: "Cromo", d: "Nerd", c: "Slang PT" },
  { p: "Marado", d: "Cabeça", c: "Slang PT" },
  { p: "Curtir", d: "Diversão", c: "Slang PT" },
  { p: "Tasca", d: "Petisco", c: "Slang PT" },
  { p: "Cusco", d: "Bisbilhoteiro", c: "Slang PT" },
  { p: "Ganda", d: "Tamanho", c: "Slang PT" },

  // ──────────── GRUPO DE AMIGOS (sem pista — só o nome) ──────────────
  { p: "Rebelo", d: "", c: "Amigos" },
  { p: "Santos", d: "", c: "Amigos" },
  { p: "Marco", d: "", c: "Amigos" },
  { p: "Nuno", d: "", c: "Amigos" },
  { p: "Vitor", d: "", c: "Amigos" },
  { p: "Alex", d: "", c: "Amigos" },
  { p: "Freire", d: "", c: "Amigos" },
  { p: "Cunha", d: "", c: "Amigos" },
  { p: "Ribeiro", d: "", c: "Amigos" },
];

// Disponibiliza globalmente
if (typeof window !== "undefined") window.WORDS = WORDS;
