// Coletânea de palavras do Jogo do Impostor.
// Cada entrada: { p: palavra, d: PISTA (uma só palavra, OBLÍQUA), c: categoria }
// A pista é vista APENAS pelo impostor. Não é a característica óbvia, mas uma
// associação lateral (contexto, alcunha, consequência, símbolo) que obrigue a pensar.
// Inclui palavras de nicho e difíceis. Os nomes do grupo não têm pista (d: "").

const WORDS = [
  // ───────────────────────────── ANIMAIS ─────────────────────────────
  { p: "Leão", d: "Coragem", c: "Animais" },
  { p: "Golfinho", d: "Sonar", c: "Animais" },
  { p: "Pinguim", d: "Smoking", c: "Animais" },
  { p: "Camaleão", d: "Disfarce", c: "Animais" },
  { p: "Polvo", d: "Oito", c: "Animais" },
  { p: "Morcego", d: "Radar", c: "Animais" },
  { p: "Tartaruga", d: "Lebre", c: "Animais" },
  { p: "Coruja", d: "Sabedoria", c: "Animais" },
  { p: "Formiga", d: "Cigarra", c: "Animais" },
  { p: "Caracol", d: "Baba", c: "Animais" },
  { p: "Raposa", d: "Galinheiro", c: "Animais" },
  { p: "Abelha", d: "Rainha", c: "Animais" },
  { p: "Canguru", d: "Bolso", c: "Animais" },
  { p: "Camelo", d: "Oásis", c: "Animais" },
  { p: "Borboleta", d: "Metamorfose", c: "Animais" },
  { p: "Tubarão", d: "Cinema", c: "Animais" },
  { p: "Papagaio", d: "Pirata", c: "Animais" },
  { p: "Ouriço", d: "Bola", c: "Animais" },
  { p: "Lobo", d: "Lua", c: "Animais" },
  { p: "Cavalo", d: "Xadrez", c: "Animais" },
  { p: "Ornitorrinco", d: "Bico", c: "Animais" },
  { p: "Axolote", d: "Regeneração", c: "Animais" },
  { p: "Tardígrado", d: "Espaço", c: "Animais" },
  { p: "Narval", d: "Marfim", c: "Animais" },
  { p: "Pangolim", d: "Escamas", c: "Animais" },
  { p: "Quokka", d: "Selfie", c: "Animais" },
  { p: "Suricata", d: "Sentinela", c: "Animais" },
  { p: "Lince", d: "Pincel", c: "Animais" },
  { p: "Lémure", d: "Madagáscar", c: "Animais" },
  { p: "Tucano", d: "Tropical", c: "Animais" },
  { p: "Preguiça", d: "Algas", c: "Animais" },
  { p: "Tamanduá", d: "Língua", c: "Animais" },
  { p: "Avestruz", d: "Areia", c: "Animais" },
  { p: "Hipopótamo", d: "Lama", c: "Animais" },
  { p: "Rinoceronte", d: "Chifre", c: "Animais" },
  { p: "Coala", d: "Eucalipto", c: "Animais" },
  { p: "Castor", d: "Barragem", c: "Animais" },
  { p: "Toupeira", d: "Túnel", c: "Animais" },
  { p: "Água-viva", d: "Urtiga", c: "Animais" },
  { p: "Cavalo-marinho", d: "Gravidez", c: "Animais" },
  { p: "Caranguejo", d: "Lado", c: "Animais" },
  { p: "Salamandra", d: "Fogo", c: "Animais" },
  { p: "Texugo", d: "Mel", c: "Animais" },
  { p: "Lontra", d: "Mãos", c: "Animais" },
  { p: "Foca", d: "Aplauso", c: "Animais" },
  { p: "Morsa", d: "Bigode", c: "Animais" },
  { p: "Orca", d: "Manchas", c: "Animais" },
  { p: "Baleia", d: "Canto", c: "Animais" },
  { p: "Flamingo", d: "Perna", c: "Animais" },
  { p: "Pavão", d: "Leque", c: "Animais" },
  { p: "Escorpião", d: "Veneno", c: "Animais" },
  { p: "Vagalume", d: "Brilho", c: "Animais" },
  { p: "Louva-a-deus", d: "Oração", c: "Animais" },
  { p: "Joaninha", d: "Pintas", c: "Animais" },
  { p: "Escaravelho", d: "Egito", c: "Animais" },
  { p: "Sapo", d: "Príncipe", c: "Animais" },
  { p: "Crocodilo", d: "Rio", c: "Animais" },
  { p: "Iguana", d: "Galápagos", c: "Animais" },
  { p: "Cobra", d: "Encantador", c: "Animais" },
  { p: "Esquilo", d: "Reserva", c: "Animais" },

  // ──────────────────────────── PROFISSÕES ───────────────────────────
  { p: "Bombeiro", d: "Escada", c: "Profissões" },
  { p: "Professor", d: "Recreio", c: "Profissões" },
  { p: "Cozinheiro", d: "Estrela", c: "Profissões" },
  { p: "Piloto", d: "Nuvem", c: "Profissões" },
  { p: "Médico", d: "Receita", c: "Profissões" },
  { p: "Arquiteto", d: "Maqueta", c: "Profissões" },
  { p: "Jornalista", d: "Fonte", c: "Profissões" },
  { p: "Eletricista", d: "Choque", c: "Profissões" },
  { p: "Jardineiro", d: "Estação", c: "Profissões" },
  { p: "Advogado", d: "Cláusula", c: "Profissões" },
  { p: "Astronauta", d: "Gravidade", c: "Profissões" },
  { p: "Carteiro", d: "Cão", c: "Profissões" },
  { p: "Padeiro", d: "Madrugada", c: "Profissões" },
  { p: "Polícia", d: "Multa", c: "Profissões" },
  { p: "Dentista", d: "Sorriso", c: "Profissões" },
  { p: "Pescador", d: "Paciência", c: "Profissões" },
  { p: "Barbeiro", d: "Conversa", c: "Profissões" },
  { p: "Mecânico", d: "Mancha", c: "Profissões" },
  { p: "Sommelier", d: "Taça", c: "Profissões" },
  { p: "Taxidermista", d: "Pose", c: "Profissões" },
  { p: "Coveiro", d: "Silêncio", c: "Profissões" },
  { p: "Apicultor", d: "Véu", c: "Profissões" },
  { p: "Relojoeiro", d: "Lupa", c: "Profissões" },
  { p: "Calceteiro", d: "Calçada", c: "Profissões" },
  { p: "Ferreiro", d: "Bigorna", c: "Profissões" },
  { p: "Oleiro", d: "Roda", c: "Profissões" },
  { p: "Cartógrafo", d: "Escala", c: "Profissões" },
  { p: "Costureira", d: "Dedal", c: "Profissões" },
  { p: "Talhante", d: "Cutelo", c: "Profissões" },
  { p: "Sapateiro", d: "Sola", c: "Profissões" },
  { p: "Soldador", d: "Faísca", c: "Profissões" },
  { p: "Mineiro", d: "Canário", c: "Profissões" },
  { p: "Pastor", d: "Rebanho", c: "Profissões" },
  { p: "Psicólogo", d: "Divã", c: "Profissões" },
  { p: "Contabilista", d: "Imposto", c: "Profissões" },
  { p: "Croupier", d: "Ficha", c: "Profissões" },
  { p: "Salva-vidas", d: "Maré", c: "Profissões" },
  { p: "Escultor", d: "Cinzel", c: "Profissões" },
  { p: "Domador", d: "Chicote", c: "Profissões" },
  { p: "Malabarista", d: "Queda", c: "Profissões" },
  { p: "Tipógrafo", d: "Chumbo", c: "Profissões" },
  { p: "Estivador", d: "Cais", c: "Profissões" },

  // ───────────────────────────── PLANTAS ─────────────────────────────
  { p: "Girassol", d: "Semente", c: "Plantas" },
  { p: "Cato", d: "Picada", c: "Plantas" },
  { p: "Carvalho", d: "Mesa", c: "Plantas" },
  { p: "Roseira", d: "Namorados", c: "Plantas" },
  { p: "Bambu", d: "Panda", c: "Plantas" },
  { p: "Trevo", d: "Irlanda", c: "Plantas" },
  { p: "Hortelã", d: "Mojito", c: "Plantas" },
  { p: "Videira", d: "Outono", c: "Plantas" },
  { p: "Oliveira", d: "Paz", c: "Plantas" },
  { p: "Nenúfar", d: "Monet", c: "Plantas" },
  { p: "Sequoia", d: "Califórnia", c: "Plantas" },
  { p: "Dente-de-leão", d: "Sopro", c: "Plantas" },
  { p: "Tulipa", d: "Holanda", c: "Plantas" },
  { p: "Orquídea", d: "Estufa", c: "Plantas" },
  { p: "Lavanda", d: "Provença", c: "Plantas" },
  { p: "Samambaia", d: "Jurássico", c: "Plantas" },
  { p: "Suculenta", d: "Janela", c: "Plantas" },
  { p: "Sobreiro", d: "Rolha", c: "Plantas" },
  { p: "Pinheiro", d: "Resina", c: "Plantas" },
  { p: "Castanheiro", d: "Magusto", c: "Plantas" },
  { p: "Salgueiro", d: "Choro", c: "Plantas" },
  { p: "Cedro", d: "Líbano", c: "Plantas" },
  { p: "Papoila", d: "Sono", c: "Plantas" },
  { p: "Camélia", d: "Japão", c: "Plantas" },
  { p: "Loureiro", d: "Coroa", c: "Plantas" },
  { p: "Hera", d: "Trepar", c: "Plantas" },
  { p: "Musgo", d: "Húmido", c: "Plantas" },
  { p: "Alecrim", d: "Assado", c: "Plantas" },
  { p: "Manjericão", d: "Pesto", c: "Plantas" },
  { p: "Glicínia", d: "Pérgola", c: "Plantas" },

  // ────────────────────────────── COMIDA ─────────────────────────────
  { p: "Pastel de Nata", d: "Belém", c: "Comida" },
  { p: "Bacalhau", d: "Natal", c: "Comida" },
  { p: "Francesinha", d: "Porto", c: "Comida" },
  { p: "Piza", d: "Fatia", c: "Comida" },
  { p: "Sushi", d: "Cru", c: "Comida" },
  { p: "Hambúrguer", d: "Rápido", c: "Comida" },
  { p: "Gelado", d: "Verão", c: "Comida" },
  { p: "Caldo Verde", d: "Minho", c: "Comida" },
  { p: "Chocolate", d: "Páscoa", c: "Comida" },
  { p: "Sardinha", d: "Junho", c: "Comida" },
  { p: "Esparguete", d: "Novelo", c: "Comida" },
  { p: "Café", d: "Insónia", c: "Comida" },
  { p: "Alheira", d: "Mirandela", c: "Comida" },
  { p: "Cozido", d: "Panela", c: "Comida" },
  { p: "Migas", d: "Alentejo", c: "Comida" },
  { p: "Açorda", d: "Coentros", c: "Comida" },
  { p: "Leitão", d: "Bairrada", c: "Comida" },
  { p: "Cabrito", d: "Montanha", c: "Comida" },
  { p: "Feijoada", d: "Transmontana", c: "Comida" },
  { p: "Presunto", d: "Bolota", c: "Comida" },
  { p: "Chouriço", d: "Fumeiro", c: "Comida" },
  { p: "Broa", d: "Milho", c: "Comida" },
  { p: "Bola de Berlim", d: "Creme", c: "Comida" },
  { p: "Arroz Doce", d: "Limão", c: "Comida" },
  { p: "Aletria", d: "Ceia", c: "Comida" },
  { p: "Pudim", d: "Caramelo", c: "Comida" },
  { p: "Tiramisu", d: "Mascarpone", c: "Comida" },
  { p: "Croissant", d: "França", c: "Comida" },
  { p: "Paella", d: "Valência", c: "Comida" },
  { p: "Tacos", d: "México", c: "Comida" },
  { p: "Kebab", d: "Espeto", c: "Comida" },
  { p: "Ramen", d: "Tigela", c: "Comida" },
  { p: "Curry", d: "Picante", c: "Comida" },
  { p: "Falafel", d: "Grão", c: "Comida" },
  { p: "Gnocchi", d: "Polegar", c: "Comida" },
  { p: "Risotto", d: "Cremoso", c: "Comida" },
  { p: "Fondue", d: "Suíça", c: "Comida" },
  { p: "Sopa da Pedra", d: "Almeirim", c: "Comida" },
  { p: "Queijo da Serra", d: "Amanteigado", c: "Comida" },
  { p: "Farófias", d: "Claras", c: "Comida" },

  // ─────────────────────────────── LUGARES ───────────────────────────
  { p: "Praia", d: "Toalha", c: "Lugares" },
  { p: "Aeroporto", d: "Adeus", c: "Lugares" },
  { p: "Biblioteca", d: "Sussurro", c: "Lugares" },
  { p: "Hospital", d: "Espera", c: "Lugares" },
  { p: "Ginásio", d: "Janeiro", c: "Lugares" },
  { p: "Cinema", d: "Estreia", c: "Lugares" },
  { p: "Mercado", d: "Regateio", c: "Lugares" },
  { p: "Lisboa", d: "Sete", c: "Lugares" },
  { p: "Porto", d: "Ribeira", c: "Lugares" },
  { p: "Castelo", d: "Princesa", c: "Lugares" },
  { p: "Farol", d: "Aviso", c: "Lugares" },
  { p: "Deserto", d: "Miragem", c: "Lugares" },
  { p: "Vulcão", d: "Erupção", c: "Lugares" },
  { p: "Geleira", d: "Degelo", c: "Lugares" },
  { p: "Catacumbas", d: "Ossos", c: "Lugares" },
  { p: "Mosteiro", d: "Voto", c: "Lugares" },
  { p: "Estádio", d: "Claque", c: "Lugares" },
  { p: "Aquário", d: "Vidro", c: "Lugares" },
  { p: "Planetário", d: "Cúpula", c: "Lugares" },
  { p: "Miradouro", d: "Vista", c: "Lugares" },
  { p: "Termas", d: "Vapor", c: "Lugares" },
  { p: "Catedral", d: "Vitral", c: "Lugares" },
  { p: "Labirinto", d: "Minotauro", c: "Lugares" },
  { p: "Oásis", d: "Palmeira", c: "Lugares" },
  { p: "Fiorde", d: "Vikings", c: "Lugares" },
  { p: "Savana", d: "Safari", c: "Lugares" },
  { p: "Tundra", d: "Rena", c: "Lugares" },
  { p: "Pântano", d: "Mosquito", c: "Lugares" },
  { p: "Gruta", d: "Estalactite", c: "Lugares" },
  { p: "Caverna", d: "Pinturas", c: "Lugares" },
  { p: "Ilha", d: "Náufrago", c: "Lugares" },
  { p: "Penhasco", d: "Vertigem", c: "Lugares" },
  { p: "Cratera", d: "Meteoro", c: "Lugares" },
  { p: "Recife", d: "Coral", c: "Lugares" },
  { p: "Floresta", d: "Lenha", c: "Lugares" },
  { p: "Selva", d: "Tarzan", c: "Lugares" },

  // ────────────────────────────── OBJETOS ────────────────────────────
  { p: "Guarda-chuva", d: "Esquecido", c: "Objetos" },
  { p: "Espelho", d: "Vaidade", c: "Objetos" },
  { p: "Relógio", d: "Pressa", c: "Objetos" },
  { p: "Chave", d: "Segredo", c: "Objetos" },
  { p: "Bússola", d: "Perdido", c: "Objetos" },
  { p: "Vela", d: "Aniversário", c: "Objetos" },
  { p: "Telemóvel", d: "Bateria", c: "Objetos" },
  { p: "Almofada", d: "Sonho", c: "Objetos" },
  { p: "Óculos", d: "Foco", c: "Objetos" },
  { p: "Mala", d: "Férias", c: "Objetos" },
  { p: "Ampulheta", d: "Grãos", c: "Objetos" },
  { p: "Caleidoscópio", d: "Simetria", c: "Objetos" },
  { p: "Pêndulo", d: "Hipnose", c: "Objetos" },
  { p: "Telescópio", d: "Galileu", c: "Objetos" },
  { p: "Microscópio", d: "Célula", c: "Objetos" },
  { p: "Termómetro", d: "Febre", c: "Objetos" },
  { p: "Barómetro", d: "Pressão", c: "Objetos" },
  { p: "Metrónomo", d: "Compasso", c: "Objetos" },
  { p: "Sextante", d: "Navegação", c: "Objetos" },
  { p: "Catana", d: "Samurai", c: "Objetos" },
  { p: "Besta", d: "Medieval", c: "Objetos" },
  { p: "Catapulta", d: "Cerco", c: "Objetos" },
  { p: "Tear", d: "Linha", c: "Objetos" },
  { p: "Roca", d: "Adormecer", c: "Objetos" },
  { p: "Gramofone", d: "Vinil", c: "Objetos" },
  { p: "Lanterna", d: "Escuro", c: "Objetos" },
  { p: "Castiçal", d: "Igreja", c: "Objetos" },
  { p: "Baú", d: "Tesouro", c: "Objetos" },
  { p: "Cofre", d: "Combinação", c: "Objetos" },
  { p: "Algema", d: "Pulso", c: "Objetos" },
  { p: "Bengala", d: "Apoio", c: "Objetos" },
  { p: "Monóculo", d: "Aristocrata", c: "Objetos" },
  { p: "Cartola", d: "Mágico", c: "Objetos" },
  { p: "Aljava", d: "Flechas", c: "Objetos" },
  { p: "Diapasão", d: "Afinação", c: "Objetos" },

  // ────────────────────────── CELEBRIDADES ───────────────────────────
  { p: "Cristiano Ronaldo", d: "Madeira", c: "Celebridades" },
  { p: "Lionel Messi", d: "Pulga", c: "Celebridades" },
  { p: "Beyoncé", d: "Colmeia", c: "Celebridades" },
  { p: "Elon Musk", d: "Marte", c: "Celebridades" },
  { p: "Taylor Swift", d: "Gatos", c: "Celebridades" },
  { p: "Leonardo DiCaprio", d: "Ambiente", c: "Celebridades" },
  { p: "Dwayne Johnson", d: "Pedra", c: "Celebridades" },
  { p: "Rihanna", d: "Barbados", c: "Celebridades" },
  { p: "Keanu Reeves", d: "Pílula", c: "Celebridades" },
  { p: "Lady Gaga", d: "Carne", c: "Celebridades" },
  { p: "Will Smith", d: "Estalo", c: "Celebridades" },
  { p: "Adele", d: "Lágrimas", c: "Celebridades" },
  { p: "Oprah", d: "Talk", c: "Celebridades" },
  { p: "Madonna", d: "Material", c: "Celebridades" },
  { p: "Brad Pitt", d: "Clube", c: "Celebridades" },
  { p: "Tom Cruise", d: "Missão", c: "Celebridades" },
  { p: "Johnny Depp", d: "Caribe", c: "Celebridades" },
  { p: "Scarlett Johansson", d: "Viúva", c: "Celebridades" },
  { p: "Morgan Freeman", d: "Narrador", c: "Celebridades" },
  { p: "Kanye West", d: "Polémica", c: "Celebridades" },
  { p: "Kim Kardashian", d: "Reality", c: "Celebridades" },
  { p: "Justin Bieber", d: "Bebé", c: "Celebridades" },
  { p: "Ariana Grande", d: "Cauda", c: "Celebridades" },
  { p: "Shakira", d: "Ancas", c: "Celebridades" },
  { p: "Zendaya", d: "Musa", c: "Celebridades" },
  { p: "Timothée Chalamet", d: "Especiaria", c: "Celebridades" },
  { p: "Margot Robbie", d: "Boneca", c: "Celebridades" },
  { p: "Ryan Gosling", d: "Ken", c: "Celebridades" },
  { p: "Pelé", d: "Dez", c: "Celebridades" },
  { p: "Maradona", d: "Mão", c: "Celebridades" },
  { p: "Mike Tyson", d: "Orelha", c: "Celebridades" },
  { p: "Muhammad Ali", d: "Borboleta", c: "Celebridades" },
  { p: "Usain Bolt", d: "Raio", c: "Celebridades" },
  { p: "Michael Jordan", d: "Chicago", c: "Celebridades" },

  // ───────────────────── PERSONALIDADES PORTUGUESAS ──────────────────
  { p: "Marcelo Rebelo de Sousa", d: "Banho", c: "Personalidades PT" },
  { p: "Salvador Sobral", d: "Coração", c: "Personalidades PT" },
  { p: "José Mourinho", d: "Especial", c: "Personalidades PT" },
  { p: "Amália Rodrigues", d: "Saudade", c: "Personalidades PT" },
  { p: "Luís de Camões", d: "Olho", c: "Personalidades PT" },
  { p: "Eusébio", d: "Pantera", c: "Personalidades PT" },
  { p: "Herman José", d: "Riso", c: "Personalidades PT" },
  { p: "Pedro Pascal", d: "Capacete", c: "Personalidades PT" },
  { p: "Fernando Pessoa", d: "Máscaras", c: "Personalidades PT" },
  { p: "Mariza", d: "Platina", c: "Personalidades PT" },
  { p: "Rui Costa", d: "Maestro", c: "Personalidades PT" },
  { p: "Vasco da Gama", d: "Especiarias", c: "Personalidades PT" },
  { p: "Infante D. Henrique", d: "Sagres", c: "Personalidades PT" },
  { p: "Marquês de Pombal", d: "Terramoto", c: "Personalidades PT" },
  { p: "Afonso Henriques", d: "Fundador", c: "Personalidades PT" },
  { p: "Aristides de Sousa Mendes", d: "Vistos", c: "Personalidades PT" },
  { p: "Egas Moniz", d: "Nobel", c: "Personalidades PT" },
  { p: "Calouste Gulbenkian", d: "Fundação", c: "Personalidades PT" },
  { p: "Sophia de Mello Breyner", d: "Mar", c: "Personalidades PT" },
  { p: "José Saramago", d: "Cegueira", c: "Personalidades PT" },
  { p: "Eça de Queirós", d: "Maias", c: "Personalidades PT" },
  { p: "Florbela Espanca", d: "Sonetos", c: "Personalidades PT" },
  { p: "Bordalo Pinheiro", d: "Sátira", c: "Personalidades PT" },
  { p: "Siza Vieira", d: "Pritzker", c: "Personalidades PT" },
  { p: "Paula Rego", d: "Pintura", c: "Personalidades PT" },
  { p: "Carmen Miranda", d: "Bananas", c: "Personalidades PT" },
  { p: "Zeca Afonso", d: "Grândola", c: "Personalidades PT" },
  { p: "Carlos do Carmo", d: "Tasco", c: "Personalidades PT" },
  { p: "Tony Carreira", d: "Popular", c: "Personalidades PT" },
  { p: "Rui Veloso", d: "Chico", c: "Personalidades PT" },
  { p: "Madredeus", d: "Etérea", c: "Personalidades PT" },
  { p: "Pedro Abrunhosa", d: "Boavista", c: "Personalidades PT" },

  // ───────────────────────── ARTISTAS MUSICAIS ───────────────────────
  { p: "The Weeknd", d: "Néon", c: "Música" },
  { p: "Drake", d: "Coruja", c: "Música" },
  { p: "Billie Eilish", d: "Verde", c: "Música" },
  { p: "Bad Bunny", d: "Coelho", c: "Música" },
  { p: "Coldplay", d: "Cores", c: "Música" },
  { p: "Dua Lipa", d: "Regras", c: "Música" },
  { p: "Eminem", d: "Detroit", c: "Música" },
  { p: "Sam the Kid", d: "Almada", c: "Música" },
  { p: "Quim Barreiros", d: "Acordeão", c: "Música" },
  { p: "Xutos & Pontapés", d: "Bairro", c: "Música" },
  { p: "D.A.M.A", d: "Iniciais", c: "Música" },
  { p: "Michael Jackson", d: "Moonwalk", c: "Música" },
  { p: "Freddie Mercury", d: "Bohemian", c: "Música" },
  { p: "David Bowie", d: "Pupila", c: "Música" },
  { p: "Prince", d: "Roxo", c: "Música" },
  { p: "Elton John", d: "Piano", c: "Música" },
  { p: "Stevie Wonder", d: "Braille", c: "Música" },
  { p: "Bob Marley", d: "Jamaica", c: "Música" },
  { p: "Tupac", d: "Bandana", c: "Música" },
  { p: "Kendrick Lamar", d: "Pulitzer", c: "Música" },
  { p: "Travis Scott", d: "Cactus", c: "Música" },
  { p: "Lana Del Rey", d: "Melancolia", c: "Música" },
  { p: "Arctic Monkeys", d: "Sheffield", c: "Música" },
  { p: "Nirvana", d: "Flanela", c: "Música" },
  { p: "Pink Floyd", d: "Prisma", c: "Música" },
  { p: "Led Zeppelin", d: "Dirigível", c: "Música" },
  { p: "Rolling Stones", d: "Lábios", c: "Música" },
  { p: "AC/DC", d: "Trovão", c: "Música" },
  { p: "Daft Punk", d: "Robôs", c: "Música" },
  { p: "Slow J", d: "Açúcar", c: "Música" },
  { p: "ProfJam", d: "Trap", c: "Música" },
  { p: "Plutónio", d: "Elemento", c: "Música" },
  { p: "Richie Campbell", d: "Reggae", c: "Música" },
  { p: "Nenny", d: "Amora", c: "Música" },
  { p: "Bárbara Bandeira", d: "Jovem", c: "Música" },

  // ──────────────────── FILMES, SÉRIES E PERSONAGENS ─────────────────
  { p: "Titanic", d: "Iceberg", c: "Filmes & Séries" },
  { p: "Harry Potter", d: "Cicatriz", c: "Filmes & Séries" },
  { p: "Star Wars", d: "Pai", c: "Filmes & Séries" },
  { p: "Batman", d: "Mordomo", c: "Filmes & Séries" },
  { p: "Shrek", d: "Pântano", c: "Filmes & Séries" },
  { p: "Breaking Bad", d: "Carrinha", c: "Filmes & Séries" },
  { p: "Game of Thrones", d: "Inverno", c: "Filmes & Séries" },
  { p: "Friends", d: "Sofá", c: "Filmes & Séries" },
  { p: "Stranger Things", d: "Bicicleta", c: "Filmes & Séries" },
  { p: "Toy Story", d: "Cowboy", c: "Filmes & Séries" },
  { p: "La Casa de Papel", d: "Dalí", c: "Filmes & Séries" },
  { p: "Homem-Aranha", d: "Tio", c: "Filmes & Séries" },
  { p: "Frozen", d: "Irmãs", c: "Filmes & Séries" },
  { p: "O Senhor dos Anéis", d: "Vulcão", c: "Filmes & Séries" },
  { p: "Matrix", d: "Código", c: "Filmes & Séries" },
  { p: "Inception", d: "Pião", c: "Filmes & Séries" },
  { p: "Interstellar", d: "Buraco", c: "Filmes & Séries" },
  { p: "Avatar", d: "Pandora", c: "Filmes & Séries" },
  { p: "Gladiador", d: "Coliseu", c: "Filmes & Séries" },
  { p: "Joker", d: "Gargalhada", c: "Filmes & Séries" },
  { p: "Pulp Fiction", d: "Dança", c: "Filmes & Séries" },
  { p: "Forrest Gump", d: "Bombons", c: "Filmes & Séries" },
  { p: "O Rei Leão", d: "Ciclo", c: "Filmes & Séries" },
  { p: "Procurando Nemo", d: "Anémona", c: "Filmes & Séries" },
  { p: "Up", d: "Balões", c: "Filmes & Séries" },
  { p: "Wall-E", d: "Lixo", c: "Filmes & Séries" },
  { p: "Ratatui", d: "Esgoto", c: "Filmes & Séries" },
  { p: "Os Vingadores", d: "Infinito", c: "Filmes & Séries" },
  { p: "Pantera Negra", d: "Wakanda", c: "Filmes & Séries" },
  { p: "Deadpool", d: "Boca", c: "Filmes & Séries" },
  { p: "It", d: "Medo", c: "Filmes & Séries" },
  { p: "The Office", d: "Escritório", c: "Filmes & Séries" },
  { p: "Peaky Blinders", d: "Boné", c: "Filmes & Séries" },
  { p: "The Witcher", d: "Moeda", c: "Filmes & Séries" },
  { p: "Dark", d: "Tempo", c: "Filmes & Séries" },
  { p: "Narcos", d: "Cartel", c: "Filmes & Séries" },
  { p: "Chernobyl", d: "Radiação", c: "Filmes & Séries" },
  { p: "Black Mirror", d: "Tecnologia", c: "Filmes & Séries" },
  { p: "Squid Game", d: "Dívida", c: "Filmes & Séries" },
  { p: "Wednesday", d: "Trança", c: "Filmes & Séries" },
  { p: "The Last of Us", d: "Fungo", c: "Filmes & Séries" },
  { p: "Vikings", d: "Machado", c: "Filmes & Séries" },
  { p: "Mr. Robot", d: "Hacker", c: "Filmes & Séries" },
  { p: "Better Call Saul", d: "Advogado", c: "Filmes & Séries" },

  // ───────────────── YOUTUBERS E INFLUENCERS PORTUGUESES ─────────────
  { p: "Wuant", d: "Pioneiro", c: "Youtubers PT" },
  { p: "SirKazzio", d: "Terror", c: "Youtubers PT" },
  { p: "Windoh", d: "Janela", c: "Youtubers PT" },
  { p: "Tiagovski", d: "Crítica", c: "Youtubers PT" },
  { p: "Fred (Maria Leal)", d: "Sarcasmo", c: "Youtubers PT" },
  { p: "D4rkFrame", d: "Sombra", c: "Youtubers PT" },
  { p: "Sofia Barbosa", d: "Beleza", c: "Youtubers PT" },
  { p: "Bumba na Fofinha", d: "Estrada", c: "Youtubers PT" },
  { p: "Luís e Maria", d: "Dois", c: "Youtubers PT" },
  { p: "Pi", d: "Número", c: "Youtubers PT" },
  { p: "Bruno Aleixo", d: "Aveiro", c: "Youtubers PT" },
  { p: "Vasco Palmeirim", d: "Rádio", c: "Youtubers PT" },
  { p: "Tiago Pereira", d: "Reagir", c: "Youtubers PT" },
  { p: "Maria Castel-Branco", d: "Avó", c: "Youtubers PT" },
  { p: "Romeu (PowerPoint)", d: "Apresentação", c: "Youtubers PT" },
  { p: "Esmiúça os Esketes", d: "Podcast", c: "Youtubers PT" },

  // ───────────────────────────── BRAINROT ────────────────────────────
  { p: "Skibidi", d: "Sanita", c: "Brainrot" },
  { p: "Rizz", d: "Charme", c: "Brainrot" },
  { p: "Gyatt", d: "Trás", c: "Brainrot" },
  { p: "Sigma", d: "Sozinho", c: "Brainrot" },
  { p: "Ohio", d: "Estranho", c: "Brainrot" },
  { p: "Mewing", d: "Maxilar", c: "Brainrot" },
  { p: "NPC", d: "Repetição", c: "Brainrot" },
  { p: "Goofy ahh", d: "Disney", c: "Brainrot" },
  { p: "Fanum Tax", d: "Roubo", c: "Brainrot" },
  { p: "Tralalero Tralala", d: "Ténis", c: "Brainrot" },
  { p: "Bombardiro Crocodilo", d: "Avião", c: "Brainrot" },
  { p: "Tung Tung Sahur", d: "Tambor", c: "Brainrot" },
  { p: "Aura", d: "Pontos", c: "Brainrot" },
  { p: "Gooning", d: "Horas", c: "Brainrot" },
  { p: "Gigachad", d: "Queixo", c: "Brainrot" },
  { p: "Among Us", d: "Tarefa", c: "Brainrot" },
  { p: "Cap", d: "Mentira", c: "Brainrot" },
  { p: "Based", d: "Opinião", c: "Brainrot" },
  { p: "Cringe", d: "Vergonha", c: "Brainrot" },
  { p: "Drip", d: "Estilo", c: "Brainrot" },
  { p: "Mid", d: "Mediano", c: "Brainrot" },
  { p: "Slay", d: "Arrasar", c: "Brainrot" },
  { p: "Alpha", d: "Líder", c: "Brainrot" },
  { p: "Delulu", d: "Ilusão", c: "Brainrot" },
  { p: "Glazing", d: "Elogio", c: "Brainrot" },
  { p: "GOAT", d: "Cabra", c: "Brainrot" },
  { p: "Ratio", d: "Likes", c: "Brainrot" },
  { p: "Looksmaxxing", d: "Aparência", c: "Brainrot" },
  { p: "Chimpanzini Bananini", d: "Banana", c: "Brainrot" },
  { p: "Lirilì Larilà", d: "Sandália", c: "Brainrot" },
  { p: "Capuccino Assassino", d: "Veloz", c: "Brainrot" },
  { p: "Brr Brr Patapim", d: "Árvore", c: "Brainrot" },
  { p: "Boneca Ambalabu", d: "Pneu", c: "Brainrot" },
  { p: "Touch grass", d: "Exterior", c: "Brainrot" },

  // ───────────────────────────── PORTUGAL ────────────────────────────
  { p: "Fado", d: "Casa", c: "Portugal" },
  { p: "Azulejo", d: "Fachada", c: "Portugal" },
  { p: "Saudade", d: "Tradução", c: "Portugal" },
  { p: "Galo de Barcelos", d: "Lenda", c: "Portugal" },
  { p: "25 de Abril", d: "Cravo", c: "Portugal" },
  { p: "Torre de Belém", d: "Descobrimentos", c: "Portugal" },
  { p: "Cristo Rei", d: "Braços", c: "Portugal" },
  { p: "Eléctrico 28", d: "Colina", c: "Portugal" },
  { p: "Vinho do Porto", d: "Sobremesa", c: "Portugal" },
  { p: "Tejo", d: "Margem", c: "Portugal" },
  { p: "Rancho Folclórico", d: "Aldeia", c: "Portugal" },
  { p: "Manjerico", d: "Quadra", c: "Portugal" },
  { p: "Marcha Popular", d: "Avenida", c: "Portugal" },
  { p: "Arraial", d: "Enfeites", c: "Portugal" },
  { p: "Ginjinha", d: "Óbidos", c: "Portugal" },
  { p: "Vinho Verde", d: "Fresco", c: "Portugal" },
  { p: "Bairro Alto", d: "Boémia", c: "Portugal" },
  { p: "Fátima", d: "Milagre", c: "Portugal" },
  { p: "Serra da Estrela", d: "Ski", c: "Portugal" },
  { p: "Gerês", d: "Cascata", c: "Portugal" },
  { p: "Sintra", d: "Palácio", c: "Portugal" },
  { p: "Aveiro", d: "Moliceiro", c: "Portugal" },
  { p: "Nazaré", d: "Surf", c: "Portugal" },
  { p: "Açores", d: "Baleias", c: "Portugal" },
  { p: "Algarve", d: "Falésia", c: "Portugal" },
  { p: "Douro", d: "Socalcos", c: "Portugal" },
  { p: "Feira da Ladra", d: "Usado", c: "Portugal" },
  { p: "Magusto", d: "Cartucho", c: "Portugal" },
  { p: "Pastelaria", d: "Balcão", c: "Portugal" },
  { p: "Berlenga", d: "Forte", c: "Portugal" },
  { p: "Óbidos", d: "Vila", c: "Portugal" },
  { p: "Coliseu", d: "Recreios", c: "Portugal" },
  { p: "Sé de Lisboa", d: "Bispo", c: "Portugal" },

  // ───────────────────────────── FUTEBOL ─────────────────────────────
  { p: "Benfica", d: "Águia", c: "Futebol" },
  { p: "Sporting", d: "Alvalade", c: "Futebol" },
  { p: "FC Porto", d: "Dragão", c: "Futebol" },
  { p: "Penálti", d: "Onze", c: "Futebol" },
  { p: "VAR", d: "Ecrã", c: "Futebol" },
  { p: "Hat-trick", d: "Três", c: "Futebol" },
  { p: "Árbitro", d: "Apito", c: "Futebol" },
  { p: "Seleção", d: "Vermelho", c: "Futebol" },
  { p: "Golo", d: "Rede", c: "Futebol" },
  { p: "Luís Figo", d: "Traição", c: "Futebol" },
  { p: "Pauleta", d: "Festejo", c: "Futebol" },
  { p: "Cartão Vermelho", d: "Cedo", c: "Futebol" },
  { p: "Deco", d: "Génio", c: "Futebol" },
  { p: "Pepe", d: "Veterano", c: "Futebol" },
  { p: "Bruno Fernandes", d: "Manchester", c: "Futebol" },
  { p: "Bernardo Silva", d: "Pequeno", c: "Futebol" },
  { p: "João Félix", d: "Joia", c: "Futebol" },
  { p: "Rúben Dias", d: "Central", c: "Futebol" },
  { p: "Rafael Leão", d: "Velocidade", c: "Futebol" },
  { p: "Guardiola", d: "Careca", c: "Futebol" },
  { p: "Klopp", d: "Abraço", c: "Futebol" },
  { p: "Bola de Ouro", d: "Dourado", c: "Futebol" },
  { p: "Champions", d: "Hino", c: "Futebol" },
  { p: "Caneta", d: "Humilhação", c: "Futebol" },
  { p: "Pontapé de Bicicleta", d: "Acrobacia", c: "Futebol" },
  { p: "Fora de Jogo", d: "Adiantado", c: "Futebol" },
  { p: "Guarda-redes", d: "Luvas", c: "Futebol" },
  { p: "Livre", d: "Barreira", c: "Futebol" },
  { p: "Pontapé de Canto", d: "Esquina", c: "Futebol" },
  { p: "Autogolo", d: "Engano", c: "Futebol" },
  { p: "Derby", d: "Rivalidade", c: "Futebol" },
  { p: "Claque", d: "Bancada", c: "Futebol" },
  { p: "Taça", d: "Troféu", c: "Futebol" },

  // ───────────────────────────── DROGAS ──────────────────────────────
  { p: "Cocaína", d: "Branco", c: "Drogas" },
  { p: "Heroína", d: "Agulha", c: "Drogas" },
  { p: "Ecstasy", d: "Pista", c: "Drogas" },
  { p: "LSD", d: "Viagem", c: "Drogas" },
  { p: "Cogumelos", d: "Floresta", c: "Drogas" },
  { p: "MDMA", d: "Suor", c: "Drogas" },
  { p: "Ketamina", d: "Cavalo", c: "Drogas" },
  { p: "Anfetaminas", d: "Acordado", c: "Drogas" },
  { p: "Crack", d: "Fumo", c: "Drogas" },
  { p: "Metanfetamina", d: "Cristal", c: "Drogas" },
  { p: "DMT", d: "Minutos", c: "Drogas" },
  { p: "Mescalina", d: "Cato", c: "Drogas" },
  { p: "Ayahuasca", d: "Xamã", c: "Drogas" },
  { p: "Ópio", d: "Papoila", c: "Drogas" },
  { p: "Morfina", d: "Dor", c: "Drogas" },
  { p: "Fentanil", d: "Crise", c: "Drogas" },
  { p: "Poppers", d: "Frasco", c: "Drogas" },
  { p: "Cola", d: "Saco", c: "Drogas" },
  { p: "Salvia", d: "Folha", c: "Drogas" },
  { p: "Gás Hilariante", d: "Balão", c: "Drogas" },

  // ────────────────────────────── WEED ───────────────────────────────
  { p: "Ganza", d: "Lento", c: "Weed" },
  { p: "Charro", d: "Enrolar", c: "Weed" },
  { p: "Erva", d: "Folha", c: "Weed" },
  { p: "Liamba", d: "Planta", c: "Weed" },
  { p: "Beck", d: "Pequeno", c: "Weed" },
  { p: "THC", d: "Sigla", c: "Weed" },
  { p: "Grinder", d: "Moer", c: "Weed" },
  { p: "Bong", d: "Água", c: "Weed" },
  { p: "Munchies", d: "Frigorífico", c: "Weed" },
  { p: "Bagana", d: "Resto", c: "Weed" },
  { p: "Mocas", d: "Vermelhos", c: "Weed" },
  { p: "Sativa", d: "Dia", c: "Weed" },
  { p: "Indica", d: "Noite", c: "Weed" },
  { p: "Passa", d: "Partilha", c: "Weed" },
  { p: "Mortalha", d: "Papel", c: "Weed" },
  { p: "Costo", d: "Castanho", c: "Weed" },
  { p: "Pedrado", d: "Imóvel", c: "Weed" },
  { p: "Skunk", d: "Mofeta", c: "Weed" },
  { p: "Verdete", d: "Mato", c: "Weed" },
  { p: "Ganzão", d: "Enorme", c: "Weed" },

  // ──────────────────────── SLANG PORTUGUÊS ──────────────────────────
  { p: "Fixe", d: "Aprovação", c: "Slang PT" },
  { p: "Bué", d: "Quantidade", c: "Slang PT" },
  { p: "Cota", d: "Idade", c: "Slang PT" },
  { p: "Bazar", d: "Saída", c: "Slang PT" },
  { p: "Gajo", d: "Pessoa", c: "Slang PT" },
  { p: "Piela", d: "Copos", c: "Slang PT" },
  { p: "Cromo", d: "Escola", c: "Slang PT" },
  { p: "Marado", d: "Cabeça", c: "Slang PT" },
  { p: "Curtir", d: "Diversão", c: "Slang PT" },
  { p: "Tasca", d: "Petisco", c: "Slang PT" },
  { p: "Cusco", d: "Bisbilhoteiro", c: "Slang PT" },
  { p: "Ganda", d: "Tamanho", c: "Slang PT" },
  { p: "Porreiro", d: "Agradável", c: "Slang PT" },
  { p: "Bacano", d: "Simpático", c: "Slang PT" },
  { p: "Chunga", d: "Duvidoso", c: "Slang PT" },
  { p: "Bera", d: "Péssimo", c: "Slang PT" },
  { p: "Naipe", d: "Categoria", c: "Slang PT" },
  { p: "Tótó", d: "Tonto", c: "Slang PT" },
  { p: "Bazófia", d: "Gabarolice", c: "Slang PT" },
  { p: "Borga", d: "Folia", c: "Slang PT" },
  { p: "Pinga", d: "Tinto", c: "Slang PT" },
  { p: "Bezana", d: "Excesso", c: "Slang PT" },
  { p: "Mona", d: "Dormir", c: "Slang PT" },
  { p: "Puto", d: "Garoto", c: "Slang PT" },
  { p: "Pita", d: "Rapariga", c: "Slang PT" },
  { p: "Naco", d: "Pedaço", c: "Slang PT" },
  { p: "Garina", d: "Namorada", c: "Slang PT" },
  { p: "Aldrabão", d: "Burla", c: "Slang PT" },
  { p: "Chibo", d: "Denúncia", c: "Slang PT" },
  { p: "Malta", d: "Grupo", c: "Slang PT" },
  { p: "Engonhar", d: "Lentidão", c: "Slang PT" },
  { p: "Coscuvilhice", d: "Boato", c: "Slang PT" },
  { p: "Escachar", d: "Gargalhada", c: "Slang PT" },

  // ──────────── GRUPO DE AMIGOS (sem pista — só o nome) ──────────────
  { p: "Diogo Rebelo", d: "", c: "Amigos" },
  { p: "David Santos", d: "", c: "Amigos" },
  { p: "Marco da Silva", d: "", c: "Amigos" },
  { p: "Nuno Pinto", d: "", c: "Amigos" },
  { p: "Vitor Fernandes", d: "", c: "Amigos" },
  { p: "Alex Lemos", d: "", c: "Amigos" },
  { p: "Ricardo Freire", d: "", c: "Amigos" },
  { p: "Diogo Cunha", d: "", c: "Amigos" },
  { p: "David Ribeiro", d: "", c: "Amigos" },
  { p: "João Pinto", d: "", c: "Amigos" },
];

// Disponibiliza globalmente
if (typeof window !== "undefined") window.WORDS = WORDS;
